/**
 * @fileoverview Item hook handler definition.
 *
 * At a minimum, a hook handler must define a generate function that takes
 * configuration options and a callback function as parameters. The "generate"
 * function should return the HTML code generated by the add-on.
 *
 * Other functions that the add-on may define:
 * - enhance(el, options) to set event handlers
 * - actionCallback(params, options, callback) to let the template handle the
 * user action.
 *
 * Dependencies MUST start with './' not to require any kind of path
 * normalization when the code gets built.
 */
define(['./dep'], function (dep) {
  return {
    generate: function (options, callback) {
      console.log('Debug add-on', 'generate', options);
      return callback(null, '<p>List hook of debug add-on</p>');
    },
    enhance: function (options, el) {
      console.log('Debug add-on', 'enhance', el, options);
    }
  };
});